version: '3.8'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Expose Nginx on port 8000
    depends_on:
      - application
      - accounts
      - consents
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  application:
    image: devfunapp:1.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8001:5000"
    networks:
      - app-network

  accounts:
    image: accounts:1.0
    depends_on:
      - application
    build:
      context: ./accounts
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8002:5000"
    networks:
      - app-network

  consents:
    image: consents:1.0
    build:
      context: ./consents
      dockerfile: Dockerfile
    depends_on:
      - application
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8003:5000"
    networks:
      - app-network

  db:
    image: devfun-postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - TZ=Asia/Bangkok
    ports:
      - "9200:9200"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    networks:
      - app-network
    depends_on:
      - elasticsearch

volumes:
  db_data:
networks:
  app-network:
